"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from discovery_net._cometbft.v0_40.tendermint.abci import types_pb2 as _types_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class ABCIStub:
    """NOTE: When using custom types, mind the warnings.
    https://github.com/cosmos/gogoproto/blob/master/custom_types.md#warnings-and-issues
    """

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> ABCIAsyncStub: ...
    Echo: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestEcho, _types_pb2.ResponseEcho]
    Flush: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestFlush, _types_pb2.ResponseFlush]
    Info: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestInfo, _types_pb2.ResponseInfo]
    CheckTx: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestCheckTx, _types_pb2.ResponseCheckTx]
    InsertTx: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestInsertTx, _types_pb2.ResponseInsertTx]
    ReapTxs: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestReapTxs, _types_pb2.ResponseReapTxs]
    Query: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestQuery, _types_pb2.ResponseQuery]
    Commit: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestCommit, _types_pb2.ResponseCommit]
    InitChain: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestInitChain, _types_pb2.ResponseInitChain]
    ListSnapshots: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestListSnapshots, _types_pb2.ResponseListSnapshots]
    OfferSnapshot: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestOfferSnapshot, _types_pb2.ResponseOfferSnapshot]
    LoadSnapshotChunk: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestLoadSnapshotChunk, _types_pb2.ResponseLoadSnapshotChunk]
    ApplySnapshotChunk: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestApplySnapshotChunk, _types_pb2.ResponseApplySnapshotChunk]
    PrepareProposal: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestPrepareProposal, _types_pb2.ResponsePrepareProposal]
    ProcessProposal: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestProcessProposal, _types_pb2.ResponseProcessProposal]
    ExtendVote: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestExtendVote, _types_pb2.ResponseExtendVote]
    VerifyVoteExtension: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestVerifyVoteExtension, _types_pb2.ResponseVerifyVoteExtension]
    FinalizeBlock: _grpc.UnaryUnaryMultiCallable[_types_pb2.RequestFinalizeBlock, _types_pb2.ResponseFinalizeBlock]

@_typing.type_check_only
class ABCIAsyncStub(ABCIStub):
    """NOTE: When using custom types, mind the warnings.
    https://github.com/cosmos/gogoproto/blob/master/custom_types.md#warnings-and-issues
    """

    def __init__(self, channel: _aio.Channel) -> None: ...
    Echo: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestEcho, _types_pb2.ResponseEcho]  # type: ignore[assignment]
    Flush: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestFlush, _types_pb2.ResponseFlush]  # type: ignore[assignment]
    Info: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestInfo, _types_pb2.ResponseInfo]  # type: ignore[assignment]
    CheckTx: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestCheckTx, _types_pb2.ResponseCheckTx]  # type: ignore[assignment]
    InsertTx: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestInsertTx, _types_pb2.ResponseInsertTx]  # type: ignore[assignment]
    ReapTxs: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestReapTxs, _types_pb2.ResponseReapTxs]  # type: ignore[assignment]
    Query: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestQuery, _types_pb2.ResponseQuery]  # type: ignore[assignment]
    Commit: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestCommit, _types_pb2.ResponseCommit]  # type: ignore[assignment]
    InitChain: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestInitChain, _types_pb2.ResponseInitChain]  # type: ignore[assignment]
    ListSnapshots: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestListSnapshots, _types_pb2.ResponseListSnapshots]  # type: ignore[assignment]
    OfferSnapshot: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestOfferSnapshot, _types_pb2.ResponseOfferSnapshot]  # type: ignore[assignment]
    LoadSnapshotChunk: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestLoadSnapshotChunk, _types_pb2.ResponseLoadSnapshotChunk]  # type: ignore[assignment]
    ApplySnapshotChunk: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestApplySnapshotChunk, _types_pb2.ResponseApplySnapshotChunk]  # type: ignore[assignment]
    PrepareProposal: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestPrepareProposal, _types_pb2.ResponsePrepareProposal]  # type: ignore[assignment]
    ProcessProposal: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestProcessProposal, _types_pb2.ResponseProcessProposal]  # type: ignore[assignment]
    ExtendVote: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestExtendVote, _types_pb2.ResponseExtendVote]  # type: ignore[assignment]
    VerifyVoteExtension: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestVerifyVoteExtension, _types_pb2.ResponseVerifyVoteExtension]  # type: ignore[assignment]
    FinalizeBlock: _aio.UnaryUnaryMultiCallable[_types_pb2.RequestFinalizeBlock, _types_pb2.ResponseFinalizeBlock]  # type: ignore[assignment]

class ABCIServicer:
    """NOTE: When using custom types, mind the warnings.
    https://github.com/cosmos/gogoproto/blob/master/custom_types.md#warnings-and-issues
    """

    def Echo(
        self,
        request: _types_pb2.RequestEcho,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseEcho, _abc.Awaitable[_types_pb2.ResponseEcho]]: ...

    def Flush(
        self,
        request: _types_pb2.RequestFlush,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseFlush, _abc.Awaitable[_types_pb2.ResponseFlush]]: ...

    def Info(
        self,
        request: _types_pb2.RequestInfo,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseInfo, _abc.Awaitable[_types_pb2.ResponseInfo]]: ...

    def CheckTx(
        self,
        request: _types_pb2.RequestCheckTx,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseCheckTx, _abc.Awaitable[_types_pb2.ResponseCheckTx]]: ...

    def InsertTx(
        self,
        request: _types_pb2.RequestInsertTx,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseInsertTx, _abc.Awaitable[_types_pb2.ResponseInsertTx]]: ...

    def ReapTxs(
        self,
        request: _types_pb2.RequestReapTxs,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseReapTxs, _abc.Awaitable[_types_pb2.ResponseReapTxs]]: ...

    def Query(
        self,
        request: _types_pb2.RequestQuery,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseQuery, _abc.Awaitable[_types_pb2.ResponseQuery]]: ...

    def Commit(
        self,
        request: _types_pb2.RequestCommit,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseCommit, _abc.Awaitable[_types_pb2.ResponseCommit]]: ...

    def InitChain(
        self,
        request: _types_pb2.RequestInitChain,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseInitChain, _abc.Awaitable[_types_pb2.ResponseInitChain]]: ...

    def ListSnapshots(
        self,
        request: _types_pb2.RequestListSnapshots,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseListSnapshots, _abc.Awaitable[_types_pb2.ResponseListSnapshots]]: ...

    def OfferSnapshot(
        self,
        request: _types_pb2.RequestOfferSnapshot,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseOfferSnapshot, _abc.Awaitable[_types_pb2.ResponseOfferSnapshot]]: ...

    def LoadSnapshotChunk(
        self,
        request: _types_pb2.RequestLoadSnapshotChunk,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseLoadSnapshotChunk, _abc.Awaitable[_types_pb2.ResponseLoadSnapshotChunk]]: ...

    def ApplySnapshotChunk(
        self,
        request: _types_pb2.RequestApplySnapshotChunk,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseApplySnapshotChunk, _abc.Awaitable[_types_pb2.ResponseApplySnapshotChunk]]: ...

    def PrepareProposal(
        self,
        request: _types_pb2.RequestPrepareProposal,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponsePrepareProposal, _abc.Awaitable[_types_pb2.ResponsePrepareProposal]]: ...

    def ProcessProposal(
        self,
        request: _types_pb2.RequestProcessProposal,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseProcessProposal, _abc.Awaitable[_types_pb2.ResponseProcessProposal]]: ...

    def ExtendVote(
        self,
        request: _types_pb2.RequestExtendVote,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseExtendVote, _abc.Awaitable[_types_pb2.ResponseExtendVote]]: ...

    def VerifyVoteExtension(
        self,
        request: _types_pb2.RequestVerifyVoteExtension,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseVerifyVoteExtension, _abc.Awaitable[_types_pb2.ResponseVerifyVoteExtension]]: ...

    def FinalizeBlock(
        self,
        request: _types_pb2.RequestFinalizeBlock,
        context: _ServicerContext,
    ) -> _typing.Union[_types_pb2.ResponseFinalizeBlock, _abc.Awaitable[_types_pb2.ResponseFinalizeBlock]]: ...

def add_ABCIServicer_to_server(servicer: ABCIServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
