"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from discovery_net._cometbft.v0_40.tendermint.crypto import keys_pb2 as _keys_pb2
from discovery_net._cometbft.v0_40.tendermint.crypto import proof_pb2 as _proof_pb2
from discovery_net._cometbft.v0_40.tendermint.types import params_pb2 as _params_pb2
from discovery_net._cometbft.v0_40.tendermint.types import validator_pb2 as _validator_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _CheckTxType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _CheckTxTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_CheckTxType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NEW: _CheckTxType.ValueType  # 0
    RECHECK: _CheckTxType.ValueType  # 1

class CheckTxType(_CheckTxType, metaclass=_CheckTxTypeEnumTypeWrapper): ...

NEW: CheckTxType.ValueType  # 0
RECHECK: CheckTxType.ValueType  # 1
Global___CheckTxType: _TypeAlias = CheckTxType  # noqa: Y015

class _MisbehaviorType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _MisbehaviorTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_MisbehaviorType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    UNKNOWN: _MisbehaviorType.ValueType  # 0
    DUPLICATE_VOTE: _MisbehaviorType.ValueType  # 1
    LIGHT_CLIENT_ATTACK: _MisbehaviorType.ValueType  # 2

class MisbehaviorType(_MisbehaviorType, metaclass=_MisbehaviorTypeEnumTypeWrapper): ...

UNKNOWN: MisbehaviorType.ValueType  # 0
DUPLICATE_VOTE: MisbehaviorType.ValueType  # 1
LIGHT_CLIENT_ATTACK: MisbehaviorType.ValueType  # 2
Global___MisbehaviorType: _TypeAlias = MisbehaviorType  # noqa: Y015

@_typing.final
class Request(_message.Message):
    """----------------------------------------
    Request types
    """

    DESCRIPTOR: _descriptor.Descriptor

    ECHO_FIELD_NUMBER: _builtins.int
    FLUSH_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    INIT_CHAIN_FIELD_NUMBER: _builtins.int
    QUERY_FIELD_NUMBER: _builtins.int
    CHECK_TX_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    LIST_SNAPSHOTS_FIELD_NUMBER: _builtins.int
    OFFER_SNAPSHOT_FIELD_NUMBER: _builtins.int
    LOAD_SNAPSHOT_CHUNK_FIELD_NUMBER: _builtins.int
    APPLY_SNAPSHOT_CHUNK_FIELD_NUMBER: _builtins.int
    PREPARE_PROPOSAL_FIELD_NUMBER: _builtins.int
    PROCESS_PROPOSAL_FIELD_NUMBER: _builtins.int
    EXTEND_VOTE_FIELD_NUMBER: _builtins.int
    VERIFY_VOTE_EXTENSION_FIELD_NUMBER: _builtins.int
    FINALIZE_BLOCK_FIELD_NUMBER: _builtins.int
    INSERT_TX_FIELD_NUMBER: _builtins.int
    REAP_TXS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def echo(self) -> Global___RequestEcho: ...
    @_builtins.property
    def flush(self) -> Global___RequestFlush: ...
    @_builtins.property
    def info(self) -> Global___RequestInfo: ...
    @_builtins.property
    def init_chain(self) -> Global___RequestInitChain: ...
    @_builtins.property
    def query(self) -> Global___RequestQuery: ...
    @_builtins.property
    def check_tx(self) -> Global___RequestCheckTx: ...
    @_builtins.property
    def commit(self) -> Global___RequestCommit: ...
    @_builtins.property
    def list_snapshots(self) -> Global___RequestListSnapshots: ...
    @_builtins.property
    def offer_snapshot(self) -> Global___RequestOfferSnapshot: ...
    @_builtins.property
    def load_snapshot_chunk(self) -> Global___RequestLoadSnapshotChunk: ...
    @_builtins.property
    def apply_snapshot_chunk(self) -> Global___RequestApplySnapshotChunk: ...
    @_builtins.property
    def prepare_proposal(self) -> Global___RequestPrepareProposal: ...
    @_builtins.property
    def process_proposal(self) -> Global___RequestProcessProposal: ...
    @_builtins.property
    def extend_vote(self) -> Global___RequestExtendVote: ...
    @_builtins.property
    def verify_vote_extension(self) -> Global___RequestVerifyVoteExtension: ...
    @_builtins.property
    def finalize_block(self) -> Global___RequestFinalizeBlock: ...
    @_builtins.property
    def insert_tx(self) -> Global___RequestInsertTx: ...
    @_builtins.property
    def reap_txs(self) -> Global___RequestReapTxs: ...
    def __init__(
        self,
        *,
        echo: Global___RequestEcho | None = ...,
        flush: Global___RequestFlush | None = ...,
        info: Global___RequestInfo | None = ...,
        init_chain: Global___RequestInitChain | None = ...,
        query: Global___RequestQuery | None = ...,
        check_tx: Global___RequestCheckTx | None = ...,
        commit: Global___RequestCommit | None = ...,
        list_snapshots: Global___RequestListSnapshots | None = ...,
        offer_snapshot: Global___RequestOfferSnapshot | None = ...,
        load_snapshot_chunk: Global___RequestLoadSnapshotChunk | None = ...,
        apply_snapshot_chunk: Global___RequestApplySnapshotChunk | None = ...,
        prepare_proposal: Global___RequestPrepareProposal | None = ...,
        process_proposal: Global___RequestProcessProposal | None = ...,
        extend_vote: Global___RequestExtendVote | None = ...,
        verify_vote_extension: Global___RequestVerifyVoteExtension | None = ...,
        finalize_block: Global___RequestFinalizeBlock | None = ...,
        insert_tx: Global___RequestInsertTx | None = ...,
        reap_txs: Global___RequestReapTxs | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["apply_snapshot_chunk", b"apply_snapshot_chunk", "check_tx", b"check_tx", "commit", b"commit", "echo", b"echo", "extend_vote", b"extend_vote", "finalize_block", b"finalize_block", "flush", b"flush", "info", b"info", "init_chain", b"init_chain", "insert_tx", b"insert_tx", "list_snapshots", b"list_snapshots", "load_snapshot_chunk", b"load_snapshot_chunk", "offer_snapshot", b"offer_snapshot", "prepare_proposal", b"prepare_proposal", "process_proposal", b"process_proposal", "query", b"query", "reap_txs", b"reap_txs", "value", b"value", "verify_vote_extension", b"verify_vote_extension"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["apply_snapshot_chunk", b"apply_snapshot_chunk", "check_tx", b"check_tx", "commit", b"commit", "echo", b"echo", "extend_vote", b"extend_vote", "finalize_block", b"finalize_block", "flush", b"flush", "info", b"info", "init_chain", b"init_chain", "insert_tx", b"insert_tx", "list_snapshots", b"list_snapshots", "load_snapshot_chunk", b"load_snapshot_chunk", "offer_snapshot", b"offer_snapshot", "prepare_proposal", b"prepare_proposal", "process_proposal", b"process_proposal", "query", b"query", "reap_txs", b"reap_txs", "value", b"value", "verify_vote_extension", b"verify_vote_extension"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["echo", "flush", "info", "init_chain", "query", "check_tx", "commit", "list_snapshots", "offer_snapshot", "load_snapshot_chunk", "apply_snapshot_chunk", "prepare_proposal", "process_proposal", "extend_vote", "verify_vote_extension", "finalize_block", "insert_tx", "reap_txs"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___Request: _TypeAlias = Request  # noqa: Y015

@_typing.final
class RequestEcho(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    message: _builtins.str
    def __init__(
        self,
        *,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestEcho: _TypeAlias = RequestEcho  # noqa: Y015

@_typing.final
class RequestFlush(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestFlush: _TypeAlias = RequestFlush  # noqa: Y015

@_typing.final
class RequestInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VERSION_FIELD_NUMBER: _builtins.int
    BLOCK_VERSION_FIELD_NUMBER: _builtins.int
    P2P_VERSION_FIELD_NUMBER: _builtins.int
    ABCI_VERSION_FIELD_NUMBER: _builtins.int
    version: _builtins.str
    block_version: _builtins.int
    p2p_version: _builtins.int
    abci_version: _builtins.str
    def __init__(
        self,
        *,
        version: _builtins.str = ...,
        block_version: _builtins.int = ...,
        p2p_version: _builtins.int = ...,
        abci_version: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["abci_version", b"abci_version", "block_version", b"block_version", "p2p_version", b"p2p_version", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestInfo: _TypeAlias = RequestInfo  # noqa: Y015

@_typing.final
class RequestInitChain(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIME_FIELD_NUMBER: _builtins.int
    CHAIN_ID_FIELD_NUMBER: _builtins.int
    CONSENSUS_PARAMS_FIELD_NUMBER: _builtins.int
    VALIDATORS_FIELD_NUMBER: _builtins.int
    APP_STATE_BYTES_FIELD_NUMBER: _builtins.int
    INITIAL_HEIGHT_FIELD_NUMBER: _builtins.int
    chain_id: _builtins.str
    app_state_bytes: _builtins.bytes
    initial_height: _builtins.int
    @_builtins.property
    def time(self) -> _timestamp_pb2.Timestamp: ...
    @_builtins.property
    def consensus_params(self) -> _params_pb2.ConsensusParams: ...
    @_builtins.property
    def validators(self) -> _containers.RepeatedCompositeFieldContainer[Global___ValidatorUpdate]: ...
    def __init__(
        self,
        *,
        time: _timestamp_pb2.Timestamp | None = ...,
        chain_id: _builtins.str = ...,
        consensus_params: _params_pb2.ConsensusParams | None = ...,
        validators: _abc.Iterable[Global___ValidatorUpdate] | None = ...,
        app_state_bytes: _builtins.bytes = ...,
        initial_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["consensus_params", b"consensus_params", "time", b"time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_state_bytes", b"app_state_bytes", "chain_id", b"chain_id", "consensus_params", b"consensus_params", "initial_height", b"initial_height", "time", b"time", "validators", b"validators"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestInitChain: _TypeAlias = RequestInitChain  # noqa: Y015

@_typing.final
class RequestQuery(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    PATH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    PROVE_FIELD_NUMBER: _builtins.int
    data: _builtins.bytes
    path: _builtins.str
    height: _builtins.int
    prove: _builtins.bool
    def __init__(
        self,
        *,
        data: _builtins.bytes = ...,
        path: _builtins.str = ...,
        height: _builtins.int = ...,
        prove: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "height", b"height", "path", b"path", "prove", b"prove"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestQuery: _TypeAlias = RequestQuery  # noqa: Y015

@_typing.final
class RequestCheckTx(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TX_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    tx: _builtins.bytes
    type: Global___CheckTxType.ValueType
    def __init__(
        self,
        *,
        tx: _builtins.bytes = ...,
        type: Global___CheckTxType.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tx", b"tx", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestCheckTx: _TypeAlias = RequestCheckTx  # noqa: Y015

@_typing.final
class RequestInsertTx(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TX_FIELD_NUMBER: _builtins.int
    tx: _builtins.bytes
    def __init__(
        self,
        *,
        tx: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tx", b"tx"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestInsertTx: _TypeAlias = RequestInsertTx  # noqa: Y015

@_typing.final
class RequestReapTxs(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MAX_BYTES_FIELD_NUMBER: _builtins.int
    MAX_GAS_FIELD_NUMBER: _builtins.int
    max_bytes: _builtins.int
    max_gas: _builtins.int
    def __init__(
        self,
        *,
        max_bytes: _builtins.int = ...,
        max_gas: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_bytes", b"max_bytes", "max_gas", b"max_gas"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestReapTxs: _TypeAlias = RequestReapTxs  # noqa: Y015

@_typing.final
class RequestCommit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestCommit: _TypeAlias = RequestCommit  # noqa: Y015

@_typing.final
class RequestListSnapshots(_message.Message):
    """lists available snapshots"""

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestListSnapshots: _TypeAlias = RequestListSnapshots  # noqa: Y015

@_typing.final
class RequestOfferSnapshot(_message.Message):
    """offers a snapshot to the application"""

    DESCRIPTOR: _descriptor.Descriptor

    SNAPSHOT_FIELD_NUMBER: _builtins.int
    APP_HASH_FIELD_NUMBER: _builtins.int
    app_hash: _builtins.bytes
    """light client-verified app hash for snapshot height"""
    @_builtins.property
    def snapshot(self) -> Global___Snapshot:
        """snapshot offered by peers"""

    def __init__(
        self,
        *,
        snapshot: Global___Snapshot | None = ...,
        app_hash: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["snapshot", b"snapshot"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_hash", b"app_hash", "snapshot", b"snapshot"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestOfferSnapshot: _TypeAlias = RequestOfferSnapshot  # noqa: Y015

@_typing.final
class RequestLoadSnapshotChunk(_message.Message):
    """loads a snapshot chunk"""

    DESCRIPTOR: _descriptor.Descriptor

    HEIGHT_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    CHUNK_FIELD_NUMBER: _builtins.int
    height: _builtins.int
    format: _builtins.int
    chunk: _builtins.int
    def __init__(
        self,
        *,
        height: _builtins.int = ...,
        format: _builtins.int = ...,
        chunk: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk", b"chunk", "format", b"format", "height", b"height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestLoadSnapshotChunk: _TypeAlias = RequestLoadSnapshotChunk  # noqa: Y015

@_typing.final
class RequestApplySnapshotChunk(_message.Message):
    """Applies a snapshot chunk"""

    DESCRIPTOR: _descriptor.Descriptor

    INDEX_FIELD_NUMBER: _builtins.int
    CHUNK_FIELD_NUMBER: _builtins.int
    SENDER_FIELD_NUMBER: _builtins.int
    index: _builtins.int
    chunk: _builtins.bytes
    sender: _builtins.str
    def __init__(
        self,
        *,
        index: _builtins.int = ...,
        chunk: _builtins.bytes = ...,
        sender: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk", b"chunk", "index", b"index", "sender", b"sender"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestApplySnapshotChunk: _TypeAlias = RequestApplySnapshotChunk  # noqa: Y015

@_typing.final
class RequestPrepareProposal(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MAX_TX_BYTES_FIELD_NUMBER: _builtins.int
    TXS_FIELD_NUMBER: _builtins.int
    LOCAL_LAST_COMMIT_FIELD_NUMBER: _builtins.int
    MISBEHAVIOR_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    NEXT_VALIDATORS_HASH_FIELD_NUMBER: _builtins.int
    PROPOSER_ADDRESS_FIELD_NUMBER: _builtins.int
    max_tx_bytes: _builtins.int
    """the modified transactions cannot exceed this size."""
    height: _builtins.int
    next_validators_hash: _builtins.bytes
    proposer_address: _builtins.bytes
    """address of the public key of the validator proposing the block."""
    @_builtins.property
    def txs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]:
        """txs is an array of transactions that will be included in a block,
        sent to the app for possible modifications.
        """

    @_builtins.property
    def local_last_commit(self) -> Global___ExtendedCommitInfo: ...
    @_builtins.property
    def misbehavior(self) -> _containers.RepeatedCompositeFieldContainer[Global___Misbehavior]: ...
    @_builtins.property
    def time(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        max_tx_bytes: _builtins.int = ...,
        txs: _abc.Iterable[_builtins.bytes] | None = ...,
        local_last_commit: Global___ExtendedCommitInfo | None = ...,
        misbehavior: _abc.Iterable[Global___Misbehavior] | None = ...,
        height: _builtins.int = ...,
        time: _timestamp_pb2.Timestamp | None = ...,
        next_validators_hash: _builtins.bytes = ...,
        proposer_address: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["local_last_commit", b"local_last_commit", "time", b"time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "local_last_commit", b"local_last_commit", "max_tx_bytes", b"max_tx_bytes", "misbehavior", b"misbehavior", "next_validators_hash", b"next_validators_hash", "proposer_address", b"proposer_address", "time", b"time", "txs", b"txs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestPrepareProposal: _TypeAlias = RequestPrepareProposal  # noqa: Y015

@_typing.final
class RequestProcessProposal(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TXS_FIELD_NUMBER: _builtins.int
    PROPOSED_LAST_COMMIT_FIELD_NUMBER: _builtins.int
    MISBEHAVIOR_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    NEXT_VALIDATORS_HASH_FIELD_NUMBER: _builtins.int
    PROPOSER_ADDRESS_FIELD_NUMBER: _builtins.int
    hash: _builtins.bytes
    """hash is the merkle root hash of the fields of the proposed block."""
    height: _builtins.int
    next_validators_hash: _builtins.bytes
    proposer_address: _builtins.bytes
    """address of the public key of the original proposer of the block."""
    @_builtins.property
    def txs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    @_builtins.property
    def proposed_last_commit(self) -> Global___CommitInfo: ...
    @_builtins.property
    def misbehavior(self) -> _containers.RepeatedCompositeFieldContainer[Global___Misbehavior]: ...
    @_builtins.property
    def time(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        txs: _abc.Iterable[_builtins.bytes] | None = ...,
        proposed_last_commit: Global___CommitInfo | None = ...,
        misbehavior: _abc.Iterable[Global___Misbehavior] | None = ...,
        hash: _builtins.bytes = ...,
        height: _builtins.int = ...,
        time: _timestamp_pb2.Timestamp | None = ...,
        next_validators_hash: _builtins.bytes = ...,
        proposer_address: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["proposed_last_commit", b"proposed_last_commit", "time", b"time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hash", b"hash", "height", b"height", "misbehavior", b"misbehavior", "next_validators_hash", b"next_validators_hash", "proposed_last_commit", b"proposed_last_commit", "proposer_address", b"proposer_address", "time", b"time", "txs", b"txs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestProcessProposal: _TypeAlias = RequestProcessProposal  # noqa: Y015

@_typing.final
class RequestExtendVote(_message.Message):
    """Extends a vote with application-injected data"""

    DESCRIPTOR: _descriptor.Descriptor

    HASH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    TXS_FIELD_NUMBER: _builtins.int
    PROPOSED_LAST_COMMIT_FIELD_NUMBER: _builtins.int
    MISBEHAVIOR_FIELD_NUMBER: _builtins.int
    NEXT_VALIDATORS_HASH_FIELD_NUMBER: _builtins.int
    PROPOSER_ADDRESS_FIELD_NUMBER: _builtins.int
    hash: _builtins.bytes
    """the hash of the block that this vote may be referring to"""
    height: _builtins.int
    """the height of the extended vote"""
    next_validators_hash: _builtins.bytes
    proposer_address: _builtins.bytes
    """address of the public key of the original proposer of the block."""
    @_builtins.property
    def time(self) -> _timestamp_pb2.Timestamp:
        """info of the block that this vote may be referring to"""

    @_builtins.property
    def txs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    @_builtins.property
    def proposed_last_commit(self) -> Global___CommitInfo: ...
    @_builtins.property
    def misbehavior(self) -> _containers.RepeatedCompositeFieldContainer[Global___Misbehavior]: ...
    def __init__(
        self,
        *,
        hash: _builtins.bytes = ...,
        height: _builtins.int = ...,
        time: _timestamp_pb2.Timestamp | None = ...,
        txs: _abc.Iterable[_builtins.bytes] | None = ...,
        proposed_last_commit: Global___CommitInfo | None = ...,
        misbehavior: _abc.Iterable[Global___Misbehavior] | None = ...,
        next_validators_hash: _builtins.bytes = ...,
        proposer_address: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["proposed_last_commit", b"proposed_last_commit", "time", b"time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hash", b"hash", "height", b"height", "misbehavior", b"misbehavior", "next_validators_hash", b"next_validators_hash", "proposed_last_commit", b"proposed_last_commit", "proposer_address", b"proposer_address", "time", b"time", "txs", b"txs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestExtendVote: _TypeAlias = RequestExtendVote  # noqa: Y015

@_typing.final
class RequestVerifyVoteExtension(_message.Message):
    """Verify the vote extension"""

    DESCRIPTOR: _descriptor.Descriptor

    HASH_FIELD_NUMBER: _builtins.int
    VALIDATOR_ADDRESS_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    VOTE_EXTENSION_FIELD_NUMBER: _builtins.int
    hash: _builtins.bytes
    """the hash of the block that this received vote corresponds to"""
    validator_address: _builtins.bytes
    """the validator that signed the vote extension"""
    height: _builtins.int
    vote_extension: _builtins.bytes
    def __init__(
        self,
        *,
        hash: _builtins.bytes = ...,
        validator_address: _builtins.bytes = ...,
        height: _builtins.int = ...,
        vote_extension: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["hash", b"hash", "height", b"height", "validator_address", b"validator_address", "vote_extension", b"vote_extension"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestVerifyVoteExtension: _TypeAlias = RequestVerifyVoteExtension  # noqa: Y015

@_typing.final
class RequestFinalizeBlock(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TXS_FIELD_NUMBER: _builtins.int
    DECIDED_LAST_COMMIT_FIELD_NUMBER: _builtins.int
    MISBEHAVIOR_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    NEXT_VALIDATORS_HASH_FIELD_NUMBER: _builtins.int
    PROPOSER_ADDRESS_FIELD_NUMBER: _builtins.int
    hash: _builtins.bytes
    """hash is the merkle root hash of the fields of the decided block."""
    height: _builtins.int
    next_validators_hash: _builtins.bytes
    proposer_address: _builtins.bytes
    """proposer_address is the address of the public key of the original proposer of the block."""
    @_builtins.property
    def txs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    @_builtins.property
    def decided_last_commit(self) -> Global___CommitInfo: ...
    @_builtins.property
    def misbehavior(self) -> _containers.RepeatedCompositeFieldContainer[Global___Misbehavior]: ...
    @_builtins.property
    def time(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        txs: _abc.Iterable[_builtins.bytes] | None = ...,
        decided_last_commit: Global___CommitInfo | None = ...,
        misbehavior: _abc.Iterable[Global___Misbehavior] | None = ...,
        hash: _builtins.bytes = ...,
        height: _builtins.int = ...,
        time: _timestamp_pb2.Timestamp | None = ...,
        next_validators_hash: _builtins.bytes = ...,
        proposer_address: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["decided_last_commit", b"decided_last_commit", "time", b"time"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["decided_last_commit", b"decided_last_commit", "hash", b"hash", "height", b"height", "misbehavior", b"misbehavior", "next_validators_hash", b"next_validators_hash", "proposer_address", b"proposer_address", "time", b"time", "txs", b"txs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestFinalizeBlock: _TypeAlias = RequestFinalizeBlock  # noqa: Y015

@_typing.final
class Response(_message.Message):
    """----------------------------------------
    Response types
    """

    DESCRIPTOR: _descriptor.Descriptor

    EXCEPTION_FIELD_NUMBER: _builtins.int
    ECHO_FIELD_NUMBER: _builtins.int
    FLUSH_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    INIT_CHAIN_FIELD_NUMBER: _builtins.int
    QUERY_FIELD_NUMBER: _builtins.int
    CHECK_TX_FIELD_NUMBER: _builtins.int
    COMMIT_FIELD_NUMBER: _builtins.int
    LIST_SNAPSHOTS_FIELD_NUMBER: _builtins.int
    OFFER_SNAPSHOT_FIELD_NUMBER: _builtins.int
    LOAD_SNAPSHOT_CHUNK_FIELD_NUMBER: _builtins.int
    APPLY_SNAPSHOT_CHUNK_FIELD_NUMBER: _builtins.int
    PREPARE_PROPOSAL_FIELD_NUMBER: _builtins.int
    PROCESS_PROPOSAL_FIELD_NUMBER: _builtins.int
    EXTEND_VOTE_FIELD_NUMBER: _builtins.int
    VERIFY_VOTE_EXTENSION_FIELD_NUMBER: _builtins.int
    FINALIZE_BLOCK_FIELD_NUMBER: _builtins.int
    INSERT_TX_FIELD_NUMBER: _builtins.int
    REAP_TXS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def exception(self) -> Global___ResponseException: ...
    @_builtins.property
    def echo(self) -> Global___ResponseEcho: ...
    @_builtins.property
    def flush(self) -> Global___ResponseFlush: ...
    @_builtins.property
    def info(self) -> Global___ResponseInfo: ...
    @_builtins.property
    def init_chain(self) -> Global___ResponseInitChain: ...
    @_builtins.property
    def query(self) -> Global___ResponseQuery: ...
    @_builtins.property
    def check_tx(self) -> Global___ResponseCheckTx: ...
    @_builtins.property
    def commit(self) -> Global___ResponseCommit: ...
    @_builtins.property
    def list_snapshots(self) -> Global___ResponseListSnapshots: ...
    @_builtins.property
    def offer_snapshot(self) -> Global___ResponseOfferSnapshot: ...
    @_builtins.property
    def load_snapshot_chunk(self) -> Global___ResponseLoadSnapshotChunk: ...
    @_builtins.property
    def apply_snapshot_chunk(self) -> Global___ResponseApplySnapshotChunk: ...
    @_builtins.property
    def prepare_proposal(self) -> Global___ResponsePrepareProposal: ...
    @_builtins.property
    def process_proposal(self) -> Global___ResponseProcessProposal: ...
    @_builtins.property
    def extend_vote(self) -> Global___ResponseExtendVote: ...
    @_builtins.property
    def verify_vote_extension(self) -> Global___ResponseVerifyVoteExtension: ...
    @_builtins.property
    def finalize_block(self) -> Global___ResponseFinalizeBlock: ...
    @_builtins.property
    def insert_tx(self) -> Global___ResponseInsertTx: ...
    @_builtins.property
    def reap_txs(self) -> Global___ResponseReapTxs: ...
    def __init__(
        self,
        *,
        exception: Global___ResponseException | None = ...,
        echo: Global___ResponseEcho | None = ...,
        flush: Global___ResponseFlush | None = ...,
        info: Global___ResponseInfo | None = ...,
        init_chain: Global___ResponseInitChain | None = ...,
        query: Global___ResponseQuery | None = ...,
        check_tx: Global___ResponseCheckTx | None = ...,
        commit: Global___ResponseCommit | None = ...,
        list_snapshots: Global___ResponseListSnapshots | None = ...,
        offer_snapshot: Global___ResponseOfferSnapshot | None = ...,
        load_snapshot_chunk: Global___ResponseLoadSnapshotChunk | None = ...,
        apply_snapshot_chunk: Global___ResponseApplySnapshotChunk | None = ...,
        prepare_proposal: Global___ResponsePrepareProposal | None = ...,
        process_proposal: Global___ResponseProcessProposal | None = ...,
        extend_vote: Global___ResponseExtendVote | None = ...,
        verify_vote_extension: Global___ResponseVerifyVoteExtension | None = ...,
        finalize_block: Global___ResponseFinalizeBlock | None = ...,
        insert_tx: Global___ResponseInsertTx | None = ...,
        reap_txs: Global___ResponseReapTxs | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["apply_snapshot_chunk", b"apply_snapshot_chunk", "check_tx", b"check_tx", "commit", b"commit", "echo", b"echo", "exception", b"exception", "extend_vote", b"extend_vote", "finalize_block", b"finalize_block", "flush", b"flush", "info", b"info", "init_chain", b"init_chain", "insert_tx", b"insert_tx", "list_snapshots", b"list_snapshots", "load_snapshot_chunk", b"load_snapshot_chunk", "offer_snapshot", b"offer_snapshot", "prepare_proposal", b"prepare_proposal", "process_proposal", b"process_proposal", "query", b"query", "reap_txs", b"reap_txs", "value", b"value", "verify_vote_extension", b"verify_vote_extension"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["apply_snapshot_chunk", b"apply_snapshot_chunk", "check_tx", b"check_tx", "commit", b"commit", "echo", b"echo", "exception", b"exception", "extend_vote", b"extend_vote", "finalize_block", b"finalize_block", "flush", b"flush", "info", b"info", "init_chain", b"init_chain", "insert_tx", b"insert_tx", "list_snapshots", b"list_snapshots", "load_snapshot_chunk", b"load_snapshot_chunk", "offer_snapshot", b"offer_snapshot", "prepare_proposal", b"prepare_proposal", "process_proposal", b"process_proposal", "query", b"query", "reap_txs", b"reap_txs", "value", b"value", "verify_vote_extension", b"verify_vote_extension"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_value: _TypeAlias = _typing.Literal["exception", "echo", "flush", "info", "init_chain", "query", "check_tx", "commit", "list_snapshots", "offer_snapshot", "load_snapshot_chunk", "apply_snapshot_chunk", "prepare_proposal", "process_proposal", "extend_vote", "verify_vote_extension", "finalize_block", "insert_tx", "reap_txs"]  # noqa: Y015
    _WhichOneofArgType_value: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_value) -> _WhichOneofReturnType_value | None: ...

Global___Response: _TypeAlias = Response  # noqa: Y015

@_typing.final
class ResponseException(_message.Message):
    """nondeterministic"""

    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    error: _builtins.str
    def __init__(
        self,
        *,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseException: _TypeAlias = ResponseException  # noqa: Y015

@_typing.final
class ResponseEcho(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MESSAGE_FIELD_NUMBER: _builtins.int
    message: _builtins.str
    def __init__(
        self,
        *,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseEcho: _TypeAlias = ResponseEcho  # noqa: Y015

@_typing.final
class ResponseFlush(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseFlush: _TypeAlias = ResponseFlush  # noqa: Y015

@_typing.final
class ResponseInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DATA_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    APP_VERSION_FIELD_NUMBER: _builtins.int
    LAST_BLOCK_HEIGHT_FIELD_NUMBER: _builtins.int
    LAST_BLOCK_APP_HASH_FIELD_NUMBER: _builtins.int
    data: _builtins.str
    version: _builtins.str
    app_version: _builtins.int
    last_block_height: _builtins.int
    last_block_app_hash: _builtins.bytes
    def __init__(
        self,
        *,
        data: _builtins.str = ...,
        version: _builtins.str = ...,
        app_version: _builtins.int = ...,
        last_block_height: _builtins.int = ...,
        last_block_app_hash: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_version", b"app_version", "data", b"data", "last_block_app_hash", b"last_block_app_hash", "last_block_height", b"last_block_height", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseInfo: _TypeAlias = ResponseInfo  # noqa: Y015

@_typing.final
class ResponseInitChain(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONSENSUS_PARAMS_FIELD_NUMBER: _builtins.int
    VALIDATORS_FIELD_NUMBER: _builtins.int
    APP_HASH_FIELD_NUMBER: _builtins.int
    app_hash: _builtins.bytes
    @_builtins.property
    def consensus_params(self) -> _params_pb2.ConsensusParams: ...
    @_builtins.property
    def validators(self) -> _containers.RepeatedCompositeFieldContainer[Global___ValidatorUpdate]: ...
    def __init__(
        self,
        *,
        consensus_params: _params_pb2.ConsensusParams | None = ...,
        validators: _abc.Iterable[Global___ValidatorUpdate] | None = ...,
        app_hash: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["consensus_params", b"consensus_params"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_hash", b"app_hash", "consensus_params", b"consensus_params", "validators", b"validators"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseInitChain: _TypeAlias = ResponseInitChain  # noqa: Y015

@_typing.final
class ResponseQuery(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    LOG_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    INDEX_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    PROOF_OPS_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    CODESPACE_FIELD_NUMBER: _builtins.int
    code: _builtins.int
    log: _builtins.str
    """bytes data = 2; // use "value" instead.
    nondeterministic
    """
    info: _builtins.str
    """nondeterministic"""
    index: _builtins.int
    key: _builtins.bytes
    value: _builtins.bytes
    height: _builtins.int
    codespace: _builtins.str
    @_builtins.property
    def proof_ops(self) -> _proof_pb2.ProofOps: ...
    def __init__(
        self,
        *,
        code: _builtins.int = ...,
        log: _builtins.str = ...,
        info: _builtins.str = ...,
        index: _builtins.int = ...,
        key: _builtins.bytes = ...,
        value: _builtins.bytes = ...,
        proof_ops: _proof_pb2.ProofOps | None = ...,
        height: _builtins.int = ...,
        codespace: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["proof_ops", b"proof_ops"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "codespace", b"codespace", "height", b"height", "index", b"index", "info", b"info", "key", b"key", "log", b"log", "proof_ops", b"proof_ops", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseQuery: _TypeAlias = ResponseQuery  # noqa: Y015

@_typing.final
class ResponseCheckTx(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    LOG_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    GAS_WANTED_FIELD_NUMBER: _builtins.int
    GAS_USED_FIELD_NUMBER: _builtins.int
    EVENTS_FIELD_NUMBER: _builtins.int
    CODESPACE_FIELD_NUMBER: _builtins.int
    code: _builtins.int
    data: _builtins.bytes
    log: _builtins.str
    """nondeterministic"""
    info: _builtins.str
    """nondeterministic"""
    gas_wanted: _builtins.int
    gas_used: _builtins.int
    codespace: _builtins.str
    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[Global___Event]: ...
    def __init__(
        self,
        *,
        code: _builtins.int = ...,
        data: _builtins.bytes = ...,
        log: _builtins.str = ...,
        info: _builtins.str = ...,
        gas_wanted: _builtins.int = ...,
        gas_used: _builtins.int = ...,
        events: _abc.Iterable[Global___Event] | None = ...,
        codespace: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "codespace", b"codespace", "data", b"data", "events", b"events", "gas_used", b"gas_used", "gas_wanted", b"gas_wanted", "info", b"info", "log", b"log"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseCheckTx: _TypeAlias = ResponseCheckTx  # noqa: Y015

@_typing.final
class ResponseInsertTx(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    code: _builtins.int
    def __init__(
        self,
        *,
        code: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseInsertTx: _TypeAlias = ResponseInsertTx  # noqa: Y015

@_typing.final
class ResponseReapTxs(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TXS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def txs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    def __init__(
        self,
        *,
        txs: _abc.Iterable[_builtins.bytes] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["txs", b"txs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseReapTxs: _TypeAlias = ResponseReapTxs  # noqa: Y015

@_typing.final
class ResponseCommit(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RETAIN_HEIGHT_FIELD_NUMBER: _builtins.int
    retain_height: _builtins.int
    def __init__(
        self,
        *,
        retain_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["retain_height", b"retain_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseCommit: _TypeAlias = ResponseCommit  # noqa: Y015

@_typing.final
class ResponseListSnapshots(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SNAPSHOTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def snapshots(self) -> _containers.RepeatedCompositeFieldContainer[Global___Snapshot]: ...
    def __init__(
        self,
        *,
        snapshots: _abc.Iterable[Global___Snapshot] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["snapshots", b"snapshots"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseListSnapshots: _TypeAlias = ResponseListSnapshots  # noqa: Y015

@_typing.final
class ResponseOfferSnapshot(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Result:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ResultEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ResponseOfferSnapshot._Result.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: ResponseOfferSnapshot._Result.ValueType  # 0
        """Unknown result, abort all snapshot restoration"""
        ACCEPT: ResponseOfferSnapshot._Result.ValueType  # 1
        """Snapshot accepted, apply chunks"""
        ABORT: ResponseOfferSnapshot._Result.ValueType  # 2
        """Abort all snapshot restoration"""
        REJECT: ResponseOfferSnapshot._Result.ValueType  # 3
        """Reject this specific snapshot, try others"""
        REJECT_FORMAT: ResponseOfferSnapshot._Result.ValueType  # 4
        """Reject all snapshots of this format, try others"""
        REJECT_SENDER: ResponseOfferSnapshot._Result.ValueType  # 5
        """Reject all snapshots from the sender(s), try others"""

    class Result(_Result, metaclass=_ResultEnumTypeWrapper): ...
    UNKNOWN: ResponseOfferSnapshot.Result.ValueType  # 0
    """Unknown result, abort all snapshot restoration"""
    ACCEPT: ResponseOfferSnapshot.Result.ValueType  # 1
    """Snapshot accepted, apply chunks"""
    ABORT: ResponseOfferSnapshot.Result.ValueType  # 2
    """Abort all snapshot restoration"""
    REJECT: ResponseOfferSnapshot.Result.ValueType  # 3
    """Reject this specific snapshot, try others"""
    REJECT_FORMAT: ResponseOfferSnapshot.Result.ValueType  # 4
    """Reject all snapshots of this format, try others"""
    REJECT_SENDER: ResponseOfferSnapshot.Result.ValueType  # 5
    """Reject all snapshots from the sender(s), try others"""

    RESULT_FIELD_NUMBER: _builtins.int
    result: Global___ResponseOfferSnapshot.Result.ValueType
    def __init__(
        self,
        *,
        result: Global___ResponseOfferSnapshot.Result.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseOfferSnapshot: _TypeAlias = ResponseOfferSnapshot  # noqa: Y015

@_typing.final
class ResponseLoadSnapshotChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CHUNK_FIELD_NUMBER: _builtins.int
    chunk: _builtins.bytes
    def __init__(
        self,
        *,
        chunk: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunk", b"chunk"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseLoadSnapshotChunk: _TypeAlias = ResponseLoadSnapshotChunk  # noqa: Y015

@_typing.final
class ResponseApplySnapshotChunk(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Result:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ResultEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ResponseApplySnapshotChunk._Result.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: ResponseApplySnapshotChunk._Result.ValueType  # 0
        """Unknown result, abort all snapshot restoration"""
        ACCEPT: ResponseApplySnapshotChunk._Result.ValueType  # 1
        """Chunk successfully accepted"""
        ABORT: ResponseApplySnapshotChunk._Result.ValueType  # 2
        """Abort all snapshot restoration"""
        RETRY: ResponseApplySnapshotChunk._Result.ValueType  # 3
        """Retry chunk (combine with refetch and reject)"""
        RETRY_SNAPSHOT: ResponseApplySnapshotChunk._Result.ValueType  # 4
        """Retry snapshot (combine with refetch and reject)"""
        REJECT_SNAPSHOT: ResponseApplySnapshotChunk._Result.ValueType  # 5
        """Reject this snapshot, try others"""

    class Result(_Result, metaclass=_ResultEnumTypeWrapper): ...
    UNKNOWN: ResponseApplySnapshotChunk.Result.ValueType  # 0
    """Unknown result, abort all snapshot restoration"""
    ACCEPT: ResponseApplySnapshotChunk.Result.ValueType  # 1
    """Chunk successfully accepted"""
    ABORT: ResponseApplySnapshotChunk.Result.ValueType  # 2
    """Abort all snapshot restoration"""
    RETRY: ResponseApplySnapshotChunk.Result.ValueType  # 3
    """Retry chunk (combine with refetch and reject)"""
    RETRY_SNAPSHOT: ResponseApplySnapshotChunk.Result.ValueType  # 4
    """Retry snapshot (combine with refetch and reject)"""
    REJECT_SNAPSHOT: ResponseApplySnapshotChunk.Result.ValueType  # 5
    """Reject this snapshot, try others"""

    RESULT_FIELD_NUMBER: _builtins.int
    REFETCH_CHUNKS_FIELD_NUMBER: _builtins.int
    REJECT_SENDERS_FIELD_NUMBER: _builtins.int
    result: Global___ResponseApplySnapshotChunk.Result.ValueType
    @_builtins.property
    def refetch_chunks(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
        """Chunks to refetch and reapply"""

    @_builtins.property
    def reject_senders(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """Chunk senders to reject and ban"""

    def __init__(
        self,
        *,
        result: Global___ResponseApplySnapshotChunk.Result.ValueType = ...,
        refetch_chunks: _abc.Iterable[_builtins.int] | None = ...,
        reject_senders: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["refetch_chunks", b"refetch_chunks", "reject_senders", b"reject_senders", "result", b"result"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseApplySnapshotChunk: _TypeAlias = ResponseApplySnapshotChunk  # noqa: Y015

@_typing.final
class ResponsePrepareProposal(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TXS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def txs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    def __init__(
        self,
        *,
        txs: _abc.Iterable[_builtins.bytes] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["txs", b"txs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponsePrepareProposal: _TypeAlias = ResponsePrepareProposal  # noqa: Y015

@_typing.final
class ResponseProcessProposal(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _ProposalStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ProposalStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ResponseProcessProposal._ProposalStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: ResponseProcessProposal._ProposalStatus.ValueType  # 0
        ACCEPT: ResponseProcessProposal._ProposalStatus.ValueType  # 1
        REJECT: ResponseProcessProposal._ProposalStatus.ValueType  # 2

    class ProposalStatus(_ProposalStatus, metaclass=_ProposalStatusEnumTypeWrapper): ...
    UNKNOWN: ResponseProcessProposal.ProposalStatus.ValueType  # 0
    ACCEPT: ResponseProcessProposal.ProposalStatus.ValueType  # 1
    REJECT: ResponseProcessProposal.ProposalStatus.ValueType  # 2

    STATUS_FIELD_NUMBER: _builtins.int
    status: Global___ResponseProcessProposal.ProposalStatus.ValueType
    def __init__(
        self,
        *,
        status: Global___ResponseProcessProposal.ProposalStatus.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseProcessProposal: _TypeAlias = ResponseProcessProposal  # noqa: Y015

@_typing.final
class ResponseExtendVote(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VOTE_EXTENSION_FIELD_NUMBER: _builtins.int
    vote_extension: _builtins.bytes
    def __init__(
        self,
        *,
        vote_extension: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["vote_extension", b"vote_extension"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseExtendVote: _TypeAlias = ResponseExtendVote  # noqa: Y015

@_typing.final
class ResponseVerifyVoteExtension(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _VerifyStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _VerifyStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[ResponseVerifyVoteExtension._VerifyStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: ResponseVerifyVoteExtension._VerifyStatus.ValueType  # 0
        ACCEPT: ResponseVerifyVoteExtension._VerifyStatus.ValueType  # 1
        REJECT: ResponseVerifyVoteExtension._VerifyStatus.ValueType  # 2
        """Rejecting the vote extension will reject the entire precommit by the sender.
        Incorrectly implementing this thus has liveness implications as it may affect
        CometBFT's ability to receive 2/3+ valid votes to finalize the block.
        Honest nodes should never be rejected.
        """

    class VerifyStatus(_VerifyStatus, metaclass=_VerifyStatusEnumTypeWrapper): ...
    UNKNOWN: ResponseVerifyVoteExtension.VerifyStatus.ValueType  # 0
    ACCEPT: ResponseVerifyVoteExtension.VerifyStatus.ValueType  # 1
    REJECT: ResponseVerifyVoteExtension.VerifyStatus.ValueType  # 2
    """Rejecting the vote extension will reject the entire precommit by the sender.
    Incorrectly implementing this thus has liveness implications as it may affect
    CometBFT's ability to receive 2/3+ valid votes to finalize the block.
    Honest nodes should never be rejected.
    """

    STATUS_FIELD_NUMBER: _builtins.int
    status: Global___ResponseVerifyVoteExtension.VerifyStatus.ValueType
    def __init__(
        self,
        *,
        status: Global___ResponseVerifyVoteExtension.VerifyStatus.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["status", b"status"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseVerifyVoteExtension: _TypeAlias = ResponseVerifyVoteExtension  # noqa: Y015

@_typing.final
class ResponseFinalizeBlock(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EVENTS_FIELD_NUMBER: _builtins.int
    TX_RESULTS_FIELD_NUMBER: _builtins.int
    VALIDATOR_UPDATES_FIELD_NUMBER: _builtins.int
    CONSENSUS_PARAM_UPDATES_FIELD_NUMBER: _builtins.int
    APP_HASH_FIELD_NUMBER: _builtins.int
    app_hash: _builtins.bytes
    """app_hash is the hash of the applications' state which is used to confirm that execution of the transactions was deterministic. It is up to the application to decide which algorithm to use."""
    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[Global___Event]:
        """set of block events emitted as part of executing the block"""

    @_builtins.property
    def tx_results(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExecTxResult]:
        """the result of executing each transaction including the events
        the particular transaction emitted. This should match the order
        of the transactions delivered in the block itself
        """

    @_builtins.property
    def validator_updates(self) -> _containers.RepeatedCompositeFieldContainer[Global___ValidatorUpdate]:
        """a list of updates to the validator set. These will reflect the validator set at current height + 2."""

    @_builtins.property
    def consensus_param_updates(self) -> _params_pb2.ConsensusParams:
        """updates to the consensus params, if any."""

    def __init__(
        self,
        *,
        events: _abc.Iterable[Global___Event] | None = ...,
        tx_results: _abc.Iterable[Global___ExecTxResult] | None = ...,
        validator_updates: _abc.Iterable[Global___ValidatorUpdate] | None = ...,
        consensus_param_updates: _params_pb2.ConsensusParams | None = ...,
        app_hash: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["consensus_param_updates", b"consensus_param_updates"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app_hash", b"app_hash", "consensus_param_updates", b"consensus_param_updates", "events", b"events", "tx_results", b"tx_results", "validator_updates", b"validator_updates"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResponseFinalizeBlock: _TypeAlias = ResponseFinalizeBlock  # noqa: Y015

@_typing.final
class CommitInfo(_message.Message):
    """----------------------------------------
    Misc.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ROUND_FIELD_NUMBER: _builtins.int
    VOTES_FIELD_NUMBER: _builtins.int
    round: _builtins.int
    @_builtins.property
    def votes(self) -> _containers.RepeatedCompositeFieldContainer[Global___VoteInfo]: ...
    def __init__(
        self,
        *,
        round: _builtins.int = ...,
        votes: _abc.Iterable[Global___VoteInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["round", b"round", "votes", b"votes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CommitInfo: _TypeAlias = CommitInfo  # noqa: Y015

@_typing.final
class ExtendedCommitInfo(_message.Message):
    """ExtendedCommitInfo is similar to CommitInfo except that it is only used in
    the PrepareProposal request such that CometBFT can provide vote extensions
    to the application.
    """

    DESCRIPTOR: _descriptor.Descriptor

    ROUND_FIELD_NUMBER: _builtins.int
    VOTES_FIELD_NUMBER: _builtins.int
    round: _builtins.int
    """The round at which the block proposer decided in the previous height."""
    @_builtins.property
    def votes(self) -> _containers.RepeatedCompositeFieldContainer[Global___ExtendedVoteInfo]:
        """List of validators' addresses in the last validator set with their voting
        information, including vote extensions.
        """

    def __init__(
        self,
        *,
        round: _builtins.int = ...,
        votes: _abc.Iterable[Global___ExtendedVoteInfo] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["round", b"round", "votes", b"votes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExtendedCommitInfo: _TypeAlias = ExtendedCommitInfo  # noqa: Y015

@_typing.final
class Event(_message.Message):
    """Event allows application developers to attach additional information to
    ResponseFinalizeBlock and ResponseCheckTx.
    Later, transactions may be queried using these events.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    ATTRIBUTES_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    @_builtins.property
    def attributes(self) -> _containers.RepeatedCompositeFieldContainer[Global___EventAttribute]: ...
    def __init__(
        self,
        *,
        type: _builtins.str = ...,
        attributes: _abc.Iterable[Global___EventAttribute] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["attributes", b"attributes", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Event: _TypeAlias = Event  # noqa: Y015

@_typing.final
class EventAttribute(_message.Message):
    """EventAttribute is a single key-value pair, associated with an event."""

    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    INDEX_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.str
    index: _builtins.bool
    """nondeterministic"""
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.str = ...,
        index: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["index", b"index", "key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EventAttribute: _TypeAlias = EventAttribute  # noqa: Y015

@_typing.final
class ExecTxResult(_message.Message):
    """ExecTxResult contains results of executing one individual transaction.

    * Its structure is equivalent to #ResponseDeliverTx which will be deprecated/deleted
    """

    DESCRIPTOR: _descriptor.Descriptor

    CODE_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    LOG_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    GAS_WANTED_FIELD_NUMBER: _builtins.int
    GAS_USED_FIELD_NUMBER: _builtins.int
    EVENTS_FIELD_NUMBER: _builtins.int
    CODESPACE_FIELD_NUMBER: _builtins.int
    code: _builtins.int
    data: _builtins.bytes
    log: _builtins.str
    """nondeterministic"""
    info: _builtins.str
    """nondeterministic"""
    gas_wanted: _builtins.int
    gas_used: _builtins.int
    codespace: _builtins.str
    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[Global___Event]:
        """nondeterministic"""

    def __init__(
        self,
        *,
        code: _builtins.int = ...,
        data: _builtins.bytes = ...,
        log: _builtins.str = ...,
        info: _builtins.str = ...,
        gas_wanted: _builtins.int = ...,
        gas_used: _builtins.int = ...,
        events: _abc.Iterable[Global___Event] | None = ...,
        codespace: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "codespace", b"codespace", "data", b"data", "events", b"events", "gas_used", b"gas_used", "gas_wanted", b"gas_wanted", "info", b"info", "log", b"log"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExecTxResult: _TypeAlias = ExecTxResult  # noqa: Y015

@_typing.final
class TxResult(_message.Message):
    """TxResult contains results of executing the transaction.

    One usage is indexing transaction results.
    """

    DESCRIPTOR: _descriptor.Descriptor

    HEIGHT_FIELD_NUMBER: _builtins.int
    INDEX_FIELD_NUMBER: _builtins.int
    TX_FIELD_NUMBER: _builtins.int
    RESULT_FIELD_NUMBER: _builtins.int
    height: _builtins.int
    index: _builtins.int
    tx: _builtins.bytes
    @_builtins.property
    def result(self) -> Global___ExecTxResult: ...
    def __init__(
        self,
        *,
        height: _builtins.int = ...,
        index: _builtins.int = ...,
        tx: _builtins.bytes = ...,
        result: Global___ExecTxResult | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["result", b"result"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "index", b"index", "result", b"result", "tx", b"tx"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TxResult: _TypeAlias = TxResult  # noqa: Y015

@_typing.final
class Validator(_message.Message):
    """----------------------------------------
    Blockchain Types
    """

    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    POWER_FIELD_NUMBER: _builtins.int
    address: _builtins.bytes
    """The first 20 bytes of SHA256(public key)"""
    power: _builtins.int
    """PubKey pub_key = 2 [(gogoproto.nullable)=false];
    The voting power
    """
    def __init__(
        self,
        *,
        address: _builtins.bytes = ...,
        power: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "power", b"power"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Validator: _TypeAlias = Validator  # noqa: Y015

@_typing.final
class ValidatorUpdate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PUB_KEY_FIELD_NUMBER: _builtins.int
    POWER_FIELD_NUMBER: _builtins.int
    power: _builtins.int
    @_builtins.property
    def pub_key(self) -> _keys_pb2.PublicKey: ...
    def __init__(
        self,
        *,
        pub_key: _keys_pb2.PublicKey | None = ...,
        power: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pub_key", b"pub_key"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["power", b"power", "pub_key", b"pub_key"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidatorUpdate: _TypeAlias = ValidatorUpdate  # noqa: Y015

@_typing.final
class VoteInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALIDATOR_FIELD_NUMBER: _builtins.int
    BLOCK_ID_FLAG_FIELD_NUMBER: _builtins.int
    block_id_flag: _validator_pb2.BlockIDFlag.ValueType
    @_builtins.property
    def validator(self) -> Global___Validator: ...
    def __init__(
        self,
        *,
        validator: Global___Validator | None = ...,
        block_id_flag: _validator_pb2.BlockIDFlag.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["validator", b"validator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["block_id_flag", b"block_id_flag", "validator", b"validator"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VoteInfo: _TypeAlias = VoteInfo  # noqa: Y015

@_typing.final
class ExtendedVoteInfo(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALIDATOR_FIELD_NUMBER: _builtins.int
    VOTE_EXTENSION_FIELD_NUMBER: _builtins.int
    EXTENSION_SIGNATURE_FIELD_NUMBER: _builtins.int
    BLOCK_ID_FLAG_FIELD_NUMBER: _builtins.int
    vote_extension: _builtins.bytes
    """Non-deterministic extension provided by the sending validator's application."""
    extension_signature: _builtins.bytes
    """Vote extension signature created by CometBFT"""
    block_id_flag: _validator_pb2.BlockIDFlag.ValueType
    """block_id_flag indicates whether the validator voted for a block, nil, or did not vote at all"""
    @_builtins.property
    def validator(self) -> Global___Validator:
        """The validator that sent the vote."""

    def __init__(
        self,
        *,
        validator: Global___Validator | None = ...,
        vote_extension: _builtins.bytes = ...,
        extension_signature: _builtins.bytes = ...,
        block_id_flag: _validator_pb2.BlockIDFlag.ValueType = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["validator", b"validator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["block_id_flag", b"block_id_flag", "extension_signature", b"extension_signature", "validator", b"validator", "vote_extension", b"vote_extension"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExtendedVoteInfo: _TypeAlias = ExtendedVoteInfo  # noqa: Y015

@_typing.final
class Misbehavior(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    VALIDATOR_FIELD_NUMBER: _builtins.int
    HEIGHT_FIELD_NUMBER: _builtins.int
    TIME_FIELD_NUMBER: _builtins.int
    TOTAL_VOTING_POWER_FIELD_NUMBER: _builtins.int
    type: Global___MisbehaviorType.ValueType
    height: _builtins.int
    """The height when the offense occurred"""
    total_voting_power: _builtins.int
    """Total voting power of the validator set in case the ABCI application does
    not store historical validators.
    https://github.com/tendermint/tendermint/issues/4581
    """
    @_builtins.property
    def validator(self) -> Global___Validator:
        """The offending validator"""

    @_builtins.property
    def time(self) -> _timestamp_pb2.Timestamp:
        """The corresponding time where the offense occurred"""

    def __init__(
        self,
        *,
        type: Global___MisbehaviorType.ValueType = ...,
        validator: Global___Validator | None = ...,
        height: _builtins.int = ...,
        time: _timestamp_pb2.Timestamp | None = ...,
        total_voting_power: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["time", b"time", "validator", b"validator"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["height", b"height", "time", b"time", "total_voting_power", b"total_voting_power", "type", b"type", "validator", b"validator"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Misbehavior: _TypeAlias = Misbehavior  # noqa: Y015

@_typing.final
class Snapshot(_message.Message):
    """----------------------------------------
    State Sync Types
    """

    DESCRIPTOR: _descriptor.Descriptor

    HEIGHT_FIELD_NUMBER: _builtins.int
    FORMAT_FIELD_NUMBER: _builtins.int
    CHUNKS_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    height: _builtins.int
    """The height at which the snapshot was taken"""
    format: _builtins.int
    """The application-specific snapshot format"""
    chunks: _builtins.int
    """Number of chunks in the snapshot"""
    hash: _builtins.bytes
    """Arbitrary snapshot hash, equal only if identical"""
    metadata: _builtins.bytes
    """Arbitrary application metadata"""
    def __init__(
        self,
        *,
        height: _builtins.int = ...,
        format: _builtins.int = ...,
        chunks: _builtins.int = ...,
        hash: _builtins.bytes = ...,
        metadata: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["chunks", b"chunks", "format", b"format", "hash", b"hash", "height", b"height", "metadata", b"metadata"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Snapshot: _TypeAlias = Snapshot  # noqa: Y015
