"""Pin pre-migration behavior using signed bytes captured before the refactor."""

from pathlib import Path

import pytest
from pydantic import BaseModel, ConfigDict

from discovery_net.entrypoints.graphql import GraphQLQueryExecutor
from discovery_net.indexing import KnowledgeGraphIndex
from discovery_net.node import (
    CometBFTCallbackHandler,
    SQLiteArtifactLedgerStore,
    TransactionValidator,
)
from discovery_net.query import KnowledgeGraphQueries
from discovery_net.wire import (
    artifact_ref,
    decode_transaction,
    encode_transaction,
    verify_envelope,
    verify_transaction,
)


class _FixtureModel(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True, strict=True)


class _Transaction(_FixtureModel):
    name: str
    wire: str
    code: int
    artifact_refs: list[str]

    @property
    def encoded(self) -> bytes:
        return self.wire.encode("utf-8")


class _Block(_FixtureModel):
    height: int
    transactions: list[_Transaction]
    state_hash: str


class _History(_FixtureModel):
    baseline_commit: str
    chain_id: str
    initial_state_hash: str
    artifact_refs: dict[str, str]
    blocks: list[_Block]
    query: str
    query_result: dict[str, object]


_HISTORY = _History.model_validate_json(
    (Path(__file__).parent / "fixtures" / "legacy_graph" / "history.json").read_bytes()
)
_ACCEPTED = [
    transaction
    for block in _HISTORY.blocks
    for transaction in block.transactions
    if transaction.code == 0
]


@pytest.mark.parametrize("record", _ACCEPTED, ids=lambda record: record.name)
def test_frozen_transactions_retain_their_bytes_signatures_and_ids(record: _Transaction) -> None:
    # Neither the input signatures nor the expected IDs are generated by the code under test.
    transaction = decode_transaction(record.encoded)

    assert encode_transaction(transaction) == record.encoded
    assert transaction.chain_id == _HISTORY.chain_id
    assert verify_transaction(transaction)
    assert all(verify_envelope(envelope) for envelope in transaction.envelopes)
    assert [
        str(artifact_ref(envelope)) for envelope in transaction.envelopes
    ] == record.artifact_refs


def test_manifest_names_cover_exactly_the_committed_artifacts() -> None:
    recorded = [reference for transaction in _ACCEPTED for reference in transaction.artifact_refs]

    assert len(recorded) == len(set(recorded))
    assert len(_HISTORY.artifact_refs.values()) == len(set(_HISTORY.artifact_refs.values()))
    assert set(recorded) == set(_HISTORY.artifact_refs.values())


def _handler(store: SQLiteArtifactLedgerStore) -> CometBFTCallbackHandler:
    return CometBFTCallbackHandler(
        validator=TransactionValidator(expected_chain_id=_HISTORY.chain_id),
        store=store,
    )


def _execute_block(handler: CometBFTCallbackHandler, block: _Block) -> None:
    previous_head = handler.committed_head()
    result = handler.finalize_block(
        height=block.height,
        transactions=tuple(transaction.encoded for transaction in block.transactions),
    )

    assert [int(result.code) for result in result.transaction_results] == [
        transaction.code for transaction in block.transactions
    ]
    assert result.state_hash.hex() == block.state_hash
    assert handler.committed_head() == previous_head
    handler.commit()
    assert handler.committed_head().height == block.height
    assert handler.committed_head().state_hash.hex() == block.state_hash


@pytest.mark.parametrize("last_height", [block.height for block in _HISTORY.blocks])
def test_frozen_block_results_positions_and_state_survive_restart(
    tmp_path: Path,
    last_height: int,
) -> None:
    path = tmp_path / "ledger.sqlite"
    store = SQLiteArtifactLedgerStore(path=path)
    handler = _handler(store)
    assert handler.committed_head().state_hash.hex() == _HISTORY.initial_state_hash

    blocks = [block for block in _HISTORY.blocks if block.height <= last_height]
    for block in blocks:
        _execute_block(handler, block)

    reopened = SQLiteArtifactLedgerStore(path=path)
    restored = _handler(reopened)
    assert restored.committed_head() == handler.committed_head()
    snapshot = reopened.load()
    assert snapshot is not None
    assert snapshot.height == last_height
    # Rejected transactions leave gaps in transaction indexes, not renumbered history.
    assert [
        (entry.height, entry.transaction_index, encode_transaction(entry.transaction))
        for entry in snapshot.entries
    ] == [
        (block.height, transaction_index, transaction.encoded)
        for block in blocks
        for transaction_index, transaction in enumerate(block.transactions)
        if transaction.code == 0
    ]

    # A resumed executor must agree with uninterrupted replay, including after an empty block.
    for block in _HISTORY.blocks:
        if block.height > last_height:
            _execute_block(restored, block)


@pytest.mark.parametrize("incremental", [False, True], ids=["rebuild", "incremental"])
def test_frozen_graph_queries_keep_topology_and_assertion_provenance(
    tmp_path: Path,
    incremental: bool,
) -> None:
    store = SQLiteArtifactLedgerStore(path=tmp_path / "ledger.sqlite")
    handler = _handler(store)
    index = KnowledgeGraphIndex()

    for block in _HISTORY.blocks:
        _execute_block(handler, block)
        snapshot = store.load()
        assert snapshot is not None
        if incremental:
            index.append(
                entries=tuple(entry for entry in snapshot.entries if entry.height == block.height),
                height=block.height,
            )
        else:
            index.refresh(snapshot)

    result = GraphQLQueryExecutor(queries=KnowledgeGraphQueries(index=index)).execute(
        _HISTORY.query
    )

    assert result.errors == ()
    assert result.data == _HISTORY.query_result
    assert [str(artifact.artifact_ref) for artifact in index.artifacts()] == [
        reference for transaction in _ACCEPTED for reference in transaction.artifact_refs
    ]
