"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import duration_pb2 as _duration_pb2
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ConsensusParams(_message.Message):
    """ConsensusParams contains consensus critical parameters that determine the
    validity of blocks.
    """

    DESCRIPTOR: _descriptor.Descriptor

    BLOCK_FIELD_NUMBER: _builtins.int
    EVIDENCE_FIELD_NUMBER: _builtins.int
    VALIDATOR_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    ABCI_FIELD_NUMBER: _builtins.int
    AUTHORITY_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def block(self) -> Global___BlockParams: ...
    @_builtins.property
    def evidence(self) -> Global___EvidenceParams: ...
    @_builtins.property
    def validator(self) -> Global___ValidatorParams: ...
    @_builtins.property
    def version(self) -> Global___VersionParams: ...
    @_builtins.property
    def abci(self) -> Global___ABCIParams: ...
    @_builtins.property
    def authority(self) -> Global___AuthorityParams: ...
    def __init__(
        self,
        *,
        block: Global___BlockParams | None = ...,
        evidence: Global___EvidenceParams | None = ...,
        validator: Global___ValidatorParams | None = ...,
        version: Global___VersionParams | None = ...,
        abci: Global___ABCIParams | None = ...,
        authority: Global___AuthorityParams | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["abci", b"abci", "authority", b"authority", "block", b"block", "evidence", b"evidence", "validator", b"validator", "version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["abci", b"abci", "authority", b"authority", "block", b"block", "evidence", b"evidence", "validator", b"validator", "version", b"version"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ConsensusParams: _TypeAlias = ConsensusParams  # noqa: Y015

@_typing.final
class BlockParams(_message.Message):
    """BlockParams contains limits on the block size."""

    DESCRIPTOR: _descriptor.Descriptor

    MAX_BYTES_FIELD_NUMBER: _builtins.int
    MAX_GAS_FIELD_NUMBER: _builtins.int
    max_bytes: _builtins.int
    """Max block size, in bytes.
    Note: must be greater than 0
    """
    max_gas: _builtins.int
    """Max gas per block.
    Note: must be greater or equal to -1
    """
    def __init__(
        self,
        *,
        max_bytes: _builtins.int = ...,
        max_gas: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_bytes", b"max_bytes", "max_gas", b"max_gas"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___BlockParams: _TypeAlias = BlockParams  # noqa: Y015

@_typing.final
class EvidenceParams(_message.Message):
    """EvidenceParams determine how we handle evidence of malfeasance."""

    DESCRIPTOR: _descriptor.Descriptor

    MAX_AGE_NUM_BLOCKS_FIELD_NUMBER: _builtins.int
    MAX_AGE_DURATION_FIELD_NUMBER: _builtins.int
    MAX_BYTES_FIELD_NUMBER: _builtins.int
    max_age_num_blocks: _builtins.int
    """Max age of evidence, in blocks.

    The basic formula for calculating this is: MaxAgeDuration / {average block
    time}.
    """
    max_bytes: _builtins.int
    """This sets the maximum size of total evidence in bytes that can be committed in a single block.
    and should fall comfortably under the max block bytes.
    Default is 1048576 or 1MB
    """
    @_builtins.property
    def max_age_duration(self) -> _duration_pb2.Duration:
        """Max age of evidence, in time.

        It should correspond with an app's "unbonding period" or other similar
        mechanism for handling [Nothing-At-Stake
        attacks](https://github.com/ethereum/wiki/wiki/Proof-of-Stake-FAQ#what-is-the-nothing-at-stake-problem-and-how-can-it-be-fixed).
        """

    def __init__(
        self,
        *,
        max_age_num_blocks: _builtins.int = ...,
        max_age_duration: _duration_pb2.Duration | None = ...,
        max_bytes: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["max_age_duration", b"max_age_duration"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["max_age_duration", b"max_age_duration", "max_age_num_blocks", b"max_age_num_blocks", "max_bytes", b"max_bytes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EvidenceParams: _TypeAlias = EvidenceParams  # noqa: Y015

@_typing.final
class ValidatorParams(_message.Message):
    """ValidatorParams restrict the public key types validators can use.
    NOTE: uses ABCI pubkey naming, not Amino names.
    """

    DESCRIPTOR: _descriptor.Descriptor

    PUB_KEY_TYPES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def pub_key_types(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        pub_key_types: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pub_key_types", b"pub_key_types"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidatorParams: _TypeAlias = ValidatorParams  # noqa: Y015

@_typing.final
class VersionParams(_message.Message):
    """VersionParams contains the ABCI application version."""

    DESCRIPTOR: _descriptor.Descriptor

    APP_FIELD_NUMBER: _builtins.int
    app: _builtins.int
    def __init__(
        self,
        *,
        app: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["app", b"app"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VersionParams: _TypeAlias = VersionParams  # noqa: Y015

@_typing.final
class HashedParams(_message.Message):
    """HashedParams is a subset of ConsensusParams.

    It is hashed into the Header.ConsensusHash.
    """

    DESCRIPTOR: _descriptor.Descriptor

    BLOCK_MAX_BYTES_FIELD_NUMBER: _builtins.int
    BLOCK_MAX_GAS_FIELD_NUMBER: _builtins.int
    block_max_bytes: _builtins.int
    block_max_gas: _builtins.int
    def __init__(
        self,
        *,
        block_max_bytes: _builtins.int = ...,
        block_max_gas: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["block_max_bytes", b"block_max_bytes", "block_max_gas", b"block_max_gas"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___HashedParams: _TypeAlias = HashedParams  # noqa: Y015

@_typing.final
class ABCIParams(_message.Message):
    """ABCIParams configure functionality specific to the Application Blockchain Interface."""

    DESCRIPTOR: _descriptor.Descriptor

    VOTE_EXTENSIONS_ENABLE_HEIGHT_FIELD_NUMBER: _builtins.int
    vote_extensions_enable_height: _builtins.int
    """vote_extensions_enable_height configures the first height during which
    vote extensions will be enabled. During this specified height, and for all
    subsequent heights, precommit messages that do not contain valid extension data
    will be considered invalid. Prior to this height, vote extensions will not
    be used or accepted by validators on the network.

    Once enabled, vote extensions will be created by the application in ExtendVote,
    passed to the application for validation in VerifyVoteExtension and given
    to the application to use when proposing a block during PrepareProposal.
    """
    def __init__(
        self,
        *,
        vote_extensions_enable_height: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["vote_extensions_enable_height", b"vote_extensions_enable_height"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ABCIParams: _TypeAlias = ABCIParams  # noqa: Y015

@_typing.final
class AuthorityParams(_message.Message):
    """AuthorityParams holds an opaque authority string to be configured and
    interpreted by the application for authorizing parameter changes outside of
    governance. CometBFT only enforces a maximum length.
    """

    DESCRIPTOR: _descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: _builtins.int
    authority: _builtins.str
    def __init__(
        self,
        *,
        authority: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["authority", b"authority"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AuthorityParams: _TypeAlias = AuthorityParams  # noqa: Y015
