"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from discovery_net._cometbft.v0_40.tendermint.crypto import keys_pb2 as _keys_pb2
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _BlockIDFlag:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _BlockIDFlagEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_BlockIDFlag.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    BLOCK_ID_FLAG_UNKNOWN: _BlockIDFlag.ValueType  # 0
    """indicates an error condition"""
    BLOCK_ID_FLAG_ABSENT: _BlockIDFlag.ValueType  # 1
    """the vote was not received"""
    BLOCK_ID_FLAG_COMMIT: _BlockIDFlag.ValueType  # 2
    """voted for the block that received the majority"""
    BLOCK_ID_FLAG_NIL: _BlockIDFlag.ValueType  # 3
    """voted for nil"""

class BlockIDFlag(_BlockIDFlag, metaclass=_BlockIDFlagEnumTypeWrapper):
    """BlockIdFlag indicates which BlockID the signature is for"""

BLOCK_ID_FLAG_UNKNOWN: BlockIDFlag.ValueType  # 0
"""indicates an error condition"""
BLOCK_ID_FLAG_ABSENT: BlockIDFlag.ValueType  # 1
"""the vote was not received"""
BLOCK_ID_FLAG_COMMIT: BlockIDFlag.ValueType  # 2
"""voted for the block that received the majority"""
BLOCK_ID_FLAG_NIL: BlockIDFlag.ValueType  # 3
"""voted for nil"""
Global___BlockIDFlag: _TypeAlias = BlockIDFlag  # noqa: Y015

@_typing.final
class ValidatorSet(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALIDATORS_FIELD_NUMBER: _builtins.int
    PROPOSER_FIELD_NUMBER: _builtins.int
    TOTAL_VOTING_POWER_FIELD_NUMBER: _builtins.int
    total_voting_power: _builtins.int
    @_builtins.property
    def validators(self) -> _containers.RepeatedCompositeFieldContainer[Global___Validator]: ...
    @_builtins.property
    def proposer(self) -> Global___Validator: ...
    def __init__(
        self,
        *,
        validators: _abc.Iterable[Global___Validator] | None = ...,
        proposer: Global___Validator | None = ...,
        total_voting_power: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["proposer", b"proposer"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["proposer", b"proposer", "total_voting_power", b"total_voting_power", "validators", b"validators"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValidatorSet: _TypeAlias = ValidatorSet  # noqa: Y015

@_typing.final
class Validator(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDRESS_FIELD_NUMBER: _builtins.int
    PUB_KEY_FIELD_NUMBER: _builtins.int
    VOTING_POWER_FIELD_NUMBER: _builtins.int
    PROPOSER_PRIORITY_FIELD_NUMBER: _builtins.int
    address: _builtins.bytes
    voting_power: _builtins.int
    proposer_priority: _builtins.int
    @_builtins.property
    def pub_key(self) -> _keys_pb2.PublicKey: ...
    def __init__(
        self,
        *,
        address: _builtins.bytes = ...,
        pub_key: _keys_pb2.PublicKey | None = ...,
        voting_power: _builtins.int = ...,
        proposer_priority: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pub_key", b"pub_key"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["address", b"address", "proposer_priority", b"proposer_priority", "pub_key", b"pub_key", "voting_power", b"voting_power"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Validator: _TypeAlias = Validator  # noqa: Y015

@_typing.final
class SimpleValidator(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PUB_KEY_FIELD_NUMBER: _builtins.int
    VOTING_POWER_FIELD_NUMBER: _builtins.int
    voting_power: _builtins.int
    @_builtins.property
    def pub_key(self) -> _keys_pb2.PublicKey: ...
    def __init__(
        self,
        *,
        pub_key: _keys_pb2.PublicKey | None = ...,
        voting_power: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pub_key", b"pub_key"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["pub_key", b"pub_key", "voting_power", b"voting_power"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SimpleValidator: _TypeAlias = SimpleValidator  # noqa: Y015
