#!/usr/bin/env bash
#
# Bind one agent to a node already described by init-node.sh.
#
#   agent-setup/init-agent.sh
#
# Ends by running a dry firing, so setup either proves itself or tells you why
# not. Nothing here reads or copies a contributor key; it only records where one
# lives and checks its permissions.

set -eu
HERE="$(cd -- "$(dirname -- "$0")" && pwd)"
REPO_ROOT="$(cd -- "$HERE/.." && pwd)"
SESSIONS="$REPO_ROOT/agent-sessions"
. "$HERE/lib/ask.sh"
require_tty "init-agent.sh"

say ""
say "  Discovery Net — bind an agent"
say "  -----------------------------"
say ""

# ------------------------------------------------------------------- the node
NODES="$(ls "$SESSIONS/bindings/nodes"/*.env 2>/dev/null || true)"
[ -n "$NODES" ] || die "no node bindings yet. Run agent-setup/init-node.sh first."
say "  Nodes described so far:"
for f in $NODES; do
  n="$(basename "$f" .env)"
  c="$(grep -m1 '^DN_CHAIN_ID=' "$f" | cut -d= -f2-)"
  note "$n  (chain $c)"
done
say ""
DEFAULT_NODE="$(basename "$(echo "$NODES" | head -1)" .env)"
while :; do
  ask NODE_NAME "Which node" "$DEFAULT_NODE"
  NODE_FILE="$SESSIONS/bindings/nodes/$NODE_NAME.env"
  [ -f "$NODE_FILE" ] && break
  bad "no such node binding: $NODE_FILE"
done
set -a; . "$NODE_FILE"; set +a
ok "chain $DN_CHAIN_ID at $DN_RPC_URL"

# ------------------------------------------------------------------- identity
say ""
ask_choice ROLE   "Role"   "research review" "research"
ask_choice RUNNER "Runner" "claude codex"    "claude"
case "$RUNNER" in
  claude) command -v claude >/dev/null 2>&1 || note "'claude' is not on PATH here — fine if agents run elsewhere" ;;
  codex)  command -v codex  >/dev/null 2>&1 || note "'codex' is not on PATH here — fine if agents run elsewhere"
          note "the Codex runner is still a stub; see CODEX-CANARY.md" ;;
esac
ask AGENT "Agent name" "$([ "$ROLE" = review ] && echo reviewer || echo researcher-1)"

# ------------------------------------------------------------------ signing key
# Recorded, never read. An unattended agent with a world-readable key is a
# finding, not a detail.
say ""
while :; do
  ask KEY "Contributor key (PEM) path" "$HOME/agent-sessions/$AGENT/contributor.pem"
  if [ ! -f "$KEY" ]; then
    bad "not found: $KEY"
    confirm "  record it anyway (you will create it before the first firing)?" && break
    continue
  fi
  MODE="$(stat -c '%a' "$KEY" 2>/dev/null || stat -f '%Lp' "$KEY" 2>/dev/null || echo '?')"
  case "$MODE" in
    600|400) ok "key present, mode $MODE" ;;
    *)       bad "key is mode $MODE — readable beyond its owner"
             confirm "  chmod 600 it now?" && { chmod 600 "$KEY"; ok "now mode 600"; } ;;
  esac
  break
done

# ---------------------------------------------------------------------- state
say ""
ask STATE "Working directory for this agent (worklog, claims, notes clone)" \
          "$HOME/agent-sessions/$AGENT"
WORKLOG="$STATE/worklog.md"
CLAIMS="$(dirname "$STATE")/claims.d"
NOTES="$STATE/discovery-net-notes"
note "worklog     $WORKLOG"
note "claims dir  $CLAIMS   (shared between agents on this box; one file each)"
note "notes clone $NOTES    (per agent, so concurrent git never collides)"
confirm "  create these now?" && { mkdir -p "$STATE" "$CLAIMS"; ok "created"; }

REVIEWED_LINE=""
if [ "$ROLE" = "review" ]; then
  REVIEWED_LINE="DN_REVIEWED=$STATE/reviewed.jsonl"
  note "review ledger $STATE/reviewed.jsonl"
fi

OUT="$SESSIONS/bindings/agents/$AGENT.env"
write_env "$OUT" <<EOF
# Agent binding for $AGENT — generated by init-agent.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Agent facts only; node facts come from bindings/nodes/$NODE_NAME.env.
# Gitignored: this names a key location on one machine.

DN_AGENT=$AGENT
DN_ROLE=$ROLE
DN_RUNNER=$RUNNER
DN_NODE_BINDING=$NODE_NAME

DN_KEY_PATH=$KEY
DN_WORKLOG=$WORKLOG
DN_CLAIMS_DIR=$CLAIMS
DN_NOTES_CLONE=$NOTES
$REVIEWED_LINE
EOF

# ------------------------------------------------------------- prove it works
say "  Checking it end to end (gates and render only — spends nothing)..."
say ""
if "$SESSIONS/run.sh" "$AGENT" --dry-run; then
  say ""
  say "  Ready. One firing:        agent-sessions/run.sh $AGENT"
  say "  What the agents are doing: agent-sessions/agentctl status"
else
  say ""
  say "  The binding is written but a gate stopped the dry run. The line above"
  say "  says which one. Fix it and re-run: agent-sessions/run.sh $AGENT --dry-run"
fi
say ""
