"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protocol Buffers for Go with Gadgets

Copyright (c) 2013, The GoGo Authors. All rights reserved.
http://github.com/cosmos/gogoproto

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pb2 as _descriptor_pb2
from google.protobuf.internal import extension_dict as _extension_dict
import builtins as _builtins

DESCRIPTOR: _descriptor.FileDescriptor

GOPROTO_ENUM_PREFIX_FIELD_NUMBER: _builtins.int
GOPROTO_ENUM_STRINGER_FIELD_NUMBER: _builtins.int
ENUM_STRINGER_FIELD_NUMBER: _builtins.int
ENUM_CUSTOMNAME_FIELD_NUMBER: _builtins.int
ENUMDECL_FIELD_NUMBER: _builtins.int
ENUMVALUE_CUSTOMNAME_FIELD_NUMBER: _builtins.int
GOPROTO_GETTERS_ALL_FIELD_NUMBER: _builtins.int
GOPROTO_ENUM_PREFIX_ALL_FIELD_NUMBER: _builtins.int
GOPROTO_STRINGER_ALL_FIELD_NUMBER: _builtins.int
VERBOSE_EQUAL_ALL_FIELD_NUMBER: _builtins.int
FACE_ALL_FIELD_NUMBER: _builtins.int
GOSTRING_ALL_FIELD_NUMBER: _builtins.int
POPULATE_ALL_FIELD_NUMBER: _builtins.int
STRINGER_ALL_FIELD_NUMBER: _builtins.int
ONLYONE_ALL_FIELD_NUMBER: _builtins.int
EQUAL_ALL_FIELD_NUMBER: _builtins.int
DESCRIPTION_ALL_FIELD_NUMBER: _builtins.int
TESTGEN_ALL_FIELD_NUMBER: _builtins.int
BENCHGEN_ALL_FIELD_NUMBER: _builtins.int
MARSHALER_ALL_FIELD_NUMBER: _builtins.int
UNMARSHALER_ALL_FIELD_NUMBER: _builtins.int
STABLE_MARSHALER_ALL_FIELD_NUMBER: _builtins.int
SIZER_ALL_FIELD_NUMBER: _builtins.int
GOPROTO_ENUM_STRINGER_ALL_FIELD_NUMBER: _builtins.int
ENUM_STRINGER_ALL_FIELD_NUMBER: _builtins.int
UNSAFE_MARSHALER_ALL_FIELD_NUMBER: _builtins.int
UNSAFE_UNMARSHALER_ALL_FIELD_NUMBER: _builtins.int
GOPROTO_EXTENSIONS_MAP_ALL_FIELD_NUMBER: _builtins.int
GOPROTO_UNRECOGNIZED_ALL_FIELD_NUMBER: _builtins.int
GOGOPROTO_IMPORT_FIELD_NUMBER: _builtins.int
PROTOSIZER_ALL_FIELD_NUMBER: _builtins.int
COMPARE_ALL_FIELD_NUMBER: _builtins.int
TYPEDECL_ALL_FIELD_NUMBER: _builtins.int
ENUMDECL_ALL_FIELD_NUMBER: _builtins.int
GOPROTO_REGISTRATION_FIELD_NUMBER: _builtins.int
MESSAGENAME_ALL_FIELD_NUMBER: _builtins.int
GOPROTO_SIZECACHE_ALL_FIELD_NUMBER: _builtins.int
GOPROTO_UNKEYED_ALL_FIELD_NUMBER: _builtins.int
GOPROTO_GETTERS_FIELD_NUMBER: _builtins.int
GOPROTO_STRINGER_FIELD_NUMBER: _builtins.int
VERBOSE_EQUAL_FIELD_NUMBER: _builtins.int
FACE_FIELD_NUMBER: _builtins.int
GOSTRING_FIELD_NUMBER: _builtins.int
POPULATE_FIELD_NUMBER: _builtins.int
STRINGER_FIELD_NUMBER: _builtins.int
ONLYONE_FIELD_NUMBER: _builtins.int
EQUAL_FIELD_NUMBER: _builtins.int
DESCRIPTION_FIELD_NUMBER: _builtins.int
TESTGEN_FIELD_NUMBER: _builtins.int
BENCHGEN_FIELD_NUMBER: _builtins.int
MARSHALER_FIELD_NUMBER: _builtins.int
UNMARSHALER_FIELD_NUMBER: _builtins.int
STABLE_MARSHALER_FIELD_NUMBER: _builtins.int
SIZER_FIELD_NUMBER: _builtins.int
UNSAFE_MARSHALER_FIELD_NUMBER: _builtins.int
UNSAFE_UNMARSHALER_FIELD_NUMBER: _builtins.int
GOPROTO_EXTENSIONS_MAP_FIELD_NUMBER: _builtins.int
GOPROTO_UNRECOGNIZED_FIELD_NUMBER: _builtins.int
PROTOSIZER_FIELD_NUMBER: _builtins.int
COMPARE_FIELD_NUMBER: _builtins.int
TYPEDECL_FIELD_NUMBER: _builtins.int
MESSAGENAME_FIELD_NUMBER: _builtins.int
GOPROTO_SIZECACHE_FIELD_NUMBER: _builtins.int
GOPROTO_UNKEYED_FIELD_NUMBER: _builtins.int
NULLABLE_FIELD_NUMBER: _builtins.int
EMBED_FIELD_NUMBER: _builtins.int
CUSTOMTYPE_FIELD_NUMBER: _builtins.int
CUSTOMNAME_FIELD_NUMBER: _builtins.int
JSONTAG_FIELD_NUMBER: _builtins.int
MORETAGS_FIELD_NUMBER: _builtins.int
CASTTYPE_FIELD_NUMBER: _builtins.int
CASTKEY_FIELD_NUMBER: _builtins.int
CASTVALUE_FIELD_NUMBER: _builtins.int
STDTIME_FIELD_NUMBER: _builtins.int
STDDURATION_FIELD_NUMBER: _builtins.int
WKTPOINTER_FIELD_NUMBER: _builtins.int
CASTREPEATED_FIELD_NUMBER: _builtins.int
goproto_enum_prefix: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.EnumOptions, _builtins.bool]
goproto_enum_stringer: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.EnumOptions, _builtins.bool]
enum_stringer: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.EnumOptions, _builtins.bool]
enum_customname: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.EnumOptions, _builtins.str]
enumdecl: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.EnumOptions, _builtins.bool]
enumvalue_customname: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.EnumValueOptions, _builtins.str]
goproto_getters_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
goproto_enum_prefix_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
goproto_stringer_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
verbose_equal_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
face_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
gostring_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
populate_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
stringer_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
onlyone_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
equal_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
description_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
testgen_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
benchgen_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
marshaler_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
unmarshaler_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
stable_marshaler_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
sizer_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
goproto_enum_stringer_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
enum_stringer_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
unsafe_marshaler_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
unsafe_unmarshaler_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
goproto_extensions_map_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
goproto_unrecognized_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
gogoproto_import: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
protosizer_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
compare_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
typedecl_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
enumdecl_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
goproto_registration: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
messagename_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
goproto_sizecache_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
goproto_unkeyed_all: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FileOptions, _builtins.bool]
goproto_getters: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
goproto_stringer: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
verbose_equal: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
face: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
gostring: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
populate: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
stringer: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
onlyone: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
equal: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
description: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
testgen: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
benchgen: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
marshaler: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
unmarshaler: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
stable_marshaler: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
sizer: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
unsafe_marshaler: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
unsafe_unmarshaler: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
goproto_extensions_map: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
goproto_unrecognized: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
protosizer: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
compare: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
typedecl: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
messagename: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
goproto_sizecache: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
goproto_unkeyed: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.MessageOptions, _builtins.bool]
nullable: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.bool]
embed: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.bool]
customtype: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.str]
customname: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.str]
jsontag: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.str]
moretags: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.str]
casttype: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.str]
castkey: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.str]
castvalue: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.str]
stdtime: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.bool]
stdduration: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.bool]
wktpointer: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.bool]
castrepeated: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.FieldOptions, _builtins.str]
