"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class PublicKey(_message.Message):
    """PublicKey defines the keys available for use with Validators"""

    DESCRIPTOR: _descriptor.Descriptor

    ED25519_FIELD_NUMBER: _builtins.int
    SECP256K1_FIELD_NUMBER: _builtins.int
    BLS12381_FIELD_NUMBER: _builtins.int
    MLDSA65_FIELD_NUMBER: _builtins.int
    SECP256K1ETH_FIELD_NUMBER: _builtins.int
    ed25519: _builtins.bytes
    secp256k1: _builtins.bytes
    bls12381: _builtins.bytes
    mldsa65: _builtins.bytes
    secp256k1eth: _builtins.bytes
    def __init__(
        self,
        *,
        ed25519: _builtins.bytes = ...,
        secp256k1: _builtins.bytes = ...,
        bls12381: _builtins.bytes = ...,
        mldsa65: _builtins.bytes = ...,
        secp256k1eth: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bls12381", b"bls12381", "ed25519", b"ed25519", "mldsa65", b"mldsa65", "secp256k1", b"secp256k1", "secp256k1eth", b"secp256k1eth", "sum", b"sum"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bls12381", b"bls12381", "ed25519", b"ed25519", "mldsa65", b"mldsa65", "secp256k1", b"secp256k1", "secp256k1eth", b"secp256k1eth", "sum", b"sum"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_sum: _TypeAlias = _typing.Literal["ed25519", "secp256k1", "bls12381", "mldsa65", "secp256k1eth"]  # noqa: Y015
    _WhichOneofArgType_sum: _TypeAlias = _typing.Literal["sum", b"sum"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_sum) -> _WhichOneofReturnType_sum | None: ...

Global___PublicKey: _TypeAlias = PublicKey  # noqa: Y015
