"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Proof(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TOTAL_FIELD_NUMBER: _builtins.int
    INDEX_FIELD_NUMBER: _builtins.int
    LEAF_HASH_FIELD_NUMBER: _builtins.int
    AUNTS_FIELD_NUMBER: _builtins.int
    total: _builtins.int
    index: _builtins.int
    leaf_hash: _builtins.bytes
    @_builtins.property
    def aunts(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
    def __init__(
        self,
        *,
        total: _builtins.int = ...,
        index: _builtins.int = ...,
        leaf_hash: _builtins.bytes = ...,
        aunts: _abc.Iterable[_builtins.bytes] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aunts", b"aunts", "index", b"index", "leaf_hash", b"leaf_hash", "total", b"total"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Proof: _TypeAlias = Proof  # noqa: Y015

@_typing.final
class ValueOp(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    PROOF_FIELD_NUMBER: _builtins.int
    key: _builtins.bytes
    """Encoded in ProofOp.Key."""
    @_builtins.property
    def proof(self) -> Global___Proof:
        """To encode in ProofOp.Data"""

    def __init__(
        self,
        *,
        key: _builtins.bytes = ...,
        proof: Global___Proof | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["proof", b"proof"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "proof", b"proof"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ValueOp: _TypeAlias = ValueOp  # noqa: Y015

@_typing.final
class DominoOp(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    INPUT_FIELD_NUMBER: _builtins.int
    OUTPUT_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    input: _builtins.str
    output: _builtins.str
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        input: _builtins.str = ...,
        output: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["input", b"input", "key", b"key", "output", b"output"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DominoOp: _TypeAlias = DominoOp  # noqa: Y015

@_typing.final
class ProofOp(_message.Message):
    """ProofOp defines an operation used for calculating Merkle root
    The data could be arbitrary format, providing necessary data
    for example neighbouring node hash
    """

    DESCRIPTOR: _descriptor.Descriptor

    TYPE_FIELD_NUMBER: _builtins.int
    KEY_FIELD_NUMBER: _builtins.int
    DATA_FIELD_NUMBER: _builtins.int
    type: _builtins.str
    key: _builtins.bytes
    data: _builtins.bytes
    def __init__(
        self,
        *,
        type: _builtins.str = ...,
        key: _builtins.bytes = ...,
        data: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["data", b"data", "key", b"key", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProofOp: _TypeAlias = ProofOp  # noqa: Y015

@_typing.final
class ProofOps(_message.Message):
    """ProofOps is Merkle proof defined by the list of ProofOps"""

    DESCRIPTOR: _descriptor.Descriptor

    OPS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def ops(self) -> _containers.RepeatedCompositeFieldContainer[Global___ProofOp]: ...
    def __init__(
        self,
        *,
        ops: _abc.Iterable[Global___ProofOp] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ops", b"ops"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ProofOps: _TypeAlias = ProofOps  # noqa: Y015
